package com.servlet.utils;

public interface Commons {

	String DEPOSIT_SELECT = "SELECT * FROM DEPOSIT WHERE DEPOSIT_ID=?";
	String ACCUONTDETAILS_SELECT = "SELECT * FROM ACCOUNT_DETAILS WHERE ACCOUNT_NUMBER=?";
	String WITHDRAWAL_SELECT = "SELECT * FROM WITHDRAWAL WHERE WITHDRAWAL_ID=?";

	String ACCOUNTDETAILS_INSERT = "INSERT INTO ACCOUNT_DETAILS VALUES (?,DEFAULT,?);";

	String AMOUNT_INSERT = "INSERT INTO AMOUNT VALUES (DEFAULT,?,?,?,?);";

	String ACCOUNTDETAILS_FIND_PK = "SELECT ACCOUNT_DETAILS_ID FROM ACCOUNT_DETAILS WHERE ACCOUNT_NUMBER=? AND PIN=?";

	String WITHDRAWAL_INSERT = "INSERT INTO WITHDRAWAL VALUES (?,?,?)";
	String DEPOSIT_INSERT = "INSERT INTO DEPOSIT VALUES (?,?,?)";
	String TRANSACTION_INSERT = "INSERT INTO TRANSACTION VALUES (DEFAULT,?,?)";

	String TRANSACTION_FIND_PK = "SELECT TRANSACTION_ID FROM TRANSACTION  where ACCOUNT_DETAILS_ID=?";

}
