package com.servlet.utils;

public interface Commons {

	String DEPOSIT_SELECT = "SELECT * FROM DEPOSIT WHERE DEPOSIT_ID=?";
	String ACCUONTDETAILS_SELECT = "SELECT * FROM ACCOUNT_DETAILS WHERE ACCOUNT_DETAILS_ID=?";
	String WITHDRAWAL_SELECT = "SELECT * FROM WITHDRAWAL WHERE ACCOUNT_DETAILS_ID=?";

}
