package com.appstechs.beans;

// default package
// Generated Feb 9, 2016 11:24:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * AccountDetails generated by hbm2java
 */
public class AccountDetails {

	private Integer accountDetailsId;
	private int accountNumber;
	private int pin;

	public AccountDetails() {
	}

	public AccountDetails(int accountNumber, int pin) {
		this.accountNumber = accountNumber;
		this.pin = pin;
	}

	public Integer getAccountDetailsId() {
		return this.accountDetailsId;
	}

	public void setAccountDetailsId(Integer accountDetailsId) {
		this.accountDetailsId = accountDetailsId;
	}

	public int getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(int accountNumber) {
		this.accountNumber = accountNumber;
	}

	public int getPin() {
		return this.pin;
	}

	public void setPin(int pin) {
		this.pin = pin;
	}

}
