package com.appstechs.beans;

// default package
// Generated Feb 9, 2016 11:24:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * Deposit generated by hbm2java
 */
public class Deposit implements java.io.Serializable {

	private Integer depositId;
	private int amount;
	private Integer accountDetailsId;

	public Deposit() {
	}

	public Deposit(int amount) {
		this.amount = amount;
	}

	public Deposit(int amount, Integer accountDetailsId) {
		this.amount = amount;
		this.accountDetailsId = accountDetailsId;
	}

	public Integer getDepositId() {
		return this.depositId;
	}

	public void setDepositId(Integer depositId) {
		this.depositId = depositId;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Integer getAccountDetailsId() {
		return this.accountDetailsId;
	}

	public void setAccountDetailsId(Integer accountDetailsId) {
		this.accountDetailsId = accountDetailsId;
	}

}
