package com.appstechs.beans;

// default package
// Generated Feb 9, 2016 11:24:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * Withdrawal generated by hbm2java
 */
public class Withdrawal {

	private int withdrawalId;
	private int amount;
	private Integer accountDetailsId;

	public Withdrawal() {
	}

	public Withdrawal(int withdrawalId, int amount) {
		this.withdrawalId = withdrawalId;
		this.amount = amount;
	}

	public Withdrawal(int withdrawalId, int amount, Integer accountDetailsId) {
		this.withdrawalId = withdrawalId;
		this.amount = amount;
		this.accountDetailsId = accountDetailsId;
	}

	public int getWithdrawalId() {
		return this.withdrawalId;
	}

	public void setWithdrawalId(int withdrawalId) {
		this.withdrawalId = withdrawalId;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Integer getAccountDetailsId() {
		return this.accountDetailsId;
	}

	public void setAccountDetailsId(Integer accountDetailsId) {
		this.accountDetailsId = accountDetailsId;
	}

}
